spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
#=======================================================================================================================
  #相关Redis配置
  redis:
    database: 5         #redis索引（默认0）
    host: 47.105.90.107
    port: 6380
    password:
    timeout: 5000
    pool:
      max-active: 8     #连接池最大连接数，使用负值没有限制
      max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8       #连接池中的最大空闲连接
      min-idle: 0       #连接池中的最小空闲连接
      timeout: 5000     #连接超时时间（毫秒）
#=======================================================================================================================
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#=======================================================================================================================
zuul:
  ignored-services: "*" #原真实服务名不再对外暴露
  routes:
    casin-sso:
      path: /sso/**
      serviceId: casin-sso
    casin-product:
      path: /product/**
      serviceId: casin-product
    casin-fastdfs:
      path: /fastdfs/**
      serviceId: casin-fastdfs
    casin-order:
      path: /order/**
      serviceId: casin-order
  ratelimit:
      enabled: true
      repository: REDIS
      policy-list:
        casin-sso:
          - limit: 10
            refresh-interval: 60
            type:
              - origin
        casin-product:
          - limit: 10
            refresh-interval: 60
            type:
              - origin
        casin-order:
          - limit: 10
            refresh-interval: 60
            type:
              - origin
  strip-prefix: true
  max:
    host:
      connections: 500
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
  add-proxy-headers: true #减少HTTP requests，再次请求从本地缓存中获取
#=======================================================================================================================
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#=======================================================================================================================
#ribbon的真实值=(ConnectionTimeout+ReadTimeout)*2，该值应当小于hystrix的timeoutInMilliseconds的值，如果大于其值会失去负载均衡(ribbon)的重试机会，而直接熔断
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#=======================================================================================================================

---

spring:
  profiles: test
#=======================================================================================================================
  #相关Redis配置
  redis:
    database: 5         #redis索引（默认0）
    host: 47.105.90.107
    port: 6380
    password:
    timeout: 5000
    pool:
      max-active: 8     #连接池最大连接数，使用负值没有限制
      max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8       #连接池中的最大空闲连接
      min-idle: 0       #连接池中的最小空闲连接
      timeout: 5000     #连接超时时间（毫秒）
#=======================================================================================================================
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#=======================================================================================================================
zuul:
  ignored-services: "*" #原真实服务名不再对外暴露
  routes:
    casin-sso:
      path: /sso/**
      serviceId: casin-sso
    casin-product:
      path: /product/**
      serviceId: casin-product
    casin-fastdfs:
      path: /fastdfs/**
      serviceId: casin-fastdfs
    casin-order:
      path: /order/**
      serviceId: casin-order
  ratelimit:
      enabled: true
      repository: REDIS
      policy-list:
        casin-sso:
          - limit: 10
            refresh-interval: 60
            type:
              - origin
        casin-product:
          - limit: 10
            refresh-interval: 60
            type:
              - origin
        casin-order:
          - limit: 10
            refresh-interval: 60
            type:
              - origin
  strip-prefix: true
  max:
    host:
      connections: 500
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
  add-proxy-headers: true #减少HTTP requests，再次请求从本地缓存中获取
#=======================================================================================================================
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#=======================================================================================================================
#ribbon的真实值=(ConnectionTimeout+ReadTimeout)*2，该值应当小于hystrix的timeoutInMilliseconds的值，如果大于其值会失去负载均衡(ribbon)的重试机会，而直接熔断
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#=======================================================================================================================