spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
#=======================================================================================================================
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
#=======================================================================================================================
#相关eureka配置
eureka:
  instance:
    prefer-ip-address: true                    #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 10      #续约更新时间间隔（秒）
    lease-expiration-duration-in-seconds: 10   #续约到期时间（秒）
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    healthcheck:
      enabled: true #健康检查
#=======================================================================================================================


