spring: 
  profiles:
    active:
    - dev
  
---
  
spring:
  profiles: dev
  application:
    name: casin-config-dev
        
---

spring:
  profiles: test
  application:
    name: casin-config-test
 

