spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev
#=======================================================================================================================
#相关eureka配置
eureka:
  instance:
    prefer-ip-address: true                    #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 10      #续约更新时间间隔（秒）
    lease-expiration-duration-in-seconds: 10   #续约到期时间（秒）
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    healthcheck:
      enabled: true #健康检查
#=======================================================================================================================
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR
#=======================================================================================================================
#Feign中开启Hystrix对服务熔断机制的AOP
feign:
  hystrix:
    enabled : true
#=======================================================================================================================
IMAGE_ACCESS_URL: http://39.107.82.223:9999/
MAX_FILE_SIZE: 1MB